# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"0\n\x0e\x46ileUploadDesc\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08objectId\x18\x02 \x01(\t\"\x1f\n\rFileUploadRes\x12\x0e\n\x06status\x18\x01 \x01(\t2;\n\nUploadFile\x12-\n\nuploadFile\x12\x0f.FileUploadDesc\x1a\x0e.FileUploadResb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEUPLOADDESC._serialized_start=15
  _FILEUPLOADDESC._serialized_end=63
  _FILEUPLOADRES._serialized_start=65
  _FILEUPLOADRES._serialized_end=96
  _UPLOADFILE._serialized_start=98
  _UPLOADFILE._serialized_end=157
# @@protoc_insertion_point(module_scope)
